document.write("I’m Vipul Konar, and I am 7 years old.<br>")
document.write("I study at Delhi Public School in the fourth standard.<br>")
document.write("My father’s name is Mr. Adhitya Konar, and my mother’s name is Mrs. Alar Konar.<br>")
document.write("I have one younger sister who studies in the first standard in the same school.<br>")
document.write("I like watching cartoons, and my favorite cartoon character is Sinchan.<br>")
document.write("I also love playing Indoor games with my sister. And, I love playing cricketwith my friends.<br>")
document.write("I am a very honest and decent boy and follow all the instructions from my parents and teachers.<br>")
document.write("I complete my homework regularly and never get late to school.<br>")
document.write("I pay attention and respect to my teachers and elders. Also, I follow every piece of advice from them.<br>")
document.write("I try to help my mother and father by keeping all the toys at the right place after playing with them.<br>")